# Tomcat
server:
  port: 8082

spring:
  # 环境 dev|test|pro
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      maxFileSize: 104857600 #100MB
      maxRequestSize: 104857600 #100MB
  rabbitmq:
    host: 192.168.3.155
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  data:
    redis:
      host: 192.168.3.155
      port: 6379
      prefix:
        activity: "vote:activity:"  # 活动状态缓存键前缀
        result: "vote:result:"      # 投票结果缓存键前缀
    mongodb:
      # 连接地址：mongodb://用户名:密码@宿主机IP:端口/数据库名?认证数据库
      uri: mongodb://root:root@192.168.3.155:27017/vote_mongo?authSource=admin
      # 说明：
      # root:root123456 → 对应 Docker 启动时设置的用户名和密码
      # localhost:27017 → 宿主机IP（若项目也在Docker中，需用容器名如“mongo-vote”）
      # vote_mongo → 项目使用的数据库名（自动创建，无需手动建）
      # authSource=admin → MongoDB 管理员认证的数据库（固定为 admin）

swagger:
  title: X-SpringBoot API
  description: API 描述
  version: 6.0.0
  author: czx
  url: https://github.com/yzcheng90/X-SpringBoot
  email: object_czx@163.com

springdoc:
  api-docs:
    enabled: false # 开启OpenApi接口
    path: /v3/api-docs  # 自定义路径，默认为 "/v3/api-docs"
  swagger-ui:
    enabled: false # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启
    path: /swagger-ui/index.html # 自定义路径，默认为"/swagger-ui/index.html"


#七牛 AK  和  SK可以去密钥管理中查询
qiniu:
  accessKey: 2222
  secretKey: 33333
  bucketName: qh-file
  domain: https://www.qiniu.com
  prefix: task

# mybaits-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    enable-sql-runner: true
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 1
      # 默认数据库表下划线命名
      table-underline: true
